id: P006977
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:33:58.855401
source_metadata:
  id: bdr:W1CZ899
  title: ཀུན་གཞིའི་ཐལ་ཕྲེང་ཡིག་ཆའི་རྗེས་སུ་འཇུག་པ་
  author: ''
  volumes:
    15636972bbf54755a2c0ecbbb4f3ab7d:
      image_group_id: I1CZ960
      title: Volume 1 of kun gzhi'i thal phreng yig cha'i rjes su 'jug pa
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
