id: P006977
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ899
  title: ཀུན་གཞིའི་ཐལ་ཕྲེང་ཡིག་ཆའི་རྗེས་སུ་འཇུག་པ་
  author: ''
  volumes:
    fac5a00ef56d45348d43492f748e1912:
      image_group_id: I1CZ960
      title: ''
      volume_number: 1
      total_pages: 90
ebook_metadata:
  title: ཀུན་གཞིའི་ཐལ་ཕྲེང་ཡིག་ཆའི་རྗེས་སུ་འཇུག་པ་
  author: ''
  sku: P006977
  cover: cover.jpg
  layers:
  - pagination
