id: I88FFC3DF
legacy_id: P006977
ocr_import_info:
  bdrc_scan_id: W1CZ899
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:01:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:40:26.678375+00:00'
last_modified: 2022-08-31 03:40:37.246971
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ899
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ899
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་གཞིའི་ཐལ་ཕྲེང་ཡིག་ཆའི་རྗེས་སུ་འཇུག་པ།
  author: བློ་བཟང་ཆོས་དབྱིངས།
statistics:
  ocr_word_mean_confidence_index: 0.5533305318257483
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I1CZ960:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ960
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ960.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5533305318257483
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
